Soru 1 – Liste Metotları
Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
• Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
• En yüksek ve en düşük notu bulun.
• Notları küçükten büyüğe sıralayın.

In [2]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

In [3]:
# Tekrar eden notları kaldırmak için set kullanıyoruz
benzersiz_notlar = set(notlar)

In [4]:
benzersiz_notlar


{76, 85, 92, 100}

In [5]:
enYuksek_not = max(benzersiz_notlar)
enDusuk_not = min(benzersiz_notlar)

In [7]:

enYuksek_not

100

In [8]:
enDusuk_not

76

Soru 2 – Sayılar
Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.
Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
Örn: 153 → 1³+5³+3³ = 153

In [11]:
def armstrong_mu(sayi):
    basamaklar = [int(rakam) for rakam in str(sayi)]
    toplam = sum(rakam ** 3 for rakam in basamaklar)
    return toplam == sayi


In [13]:
sayi = 140
if armstrong_mu(sayi):
    print(f"{sayi} bir Armstrong sayısıdır.")
else:
    print(f"{sayi} bir Armstrong sayısı değildir.")


140 bir Armstrong sayısı değildir.


Soru 3 – Kümeler
Aşağıdaki iki küme verilmiştir:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
• Ortak dilleri bulun.
• Sadece A’da olan dilleri listeleyin.
• İki kümenin birleşimini alfabetik olarak yazdırın.

In [14]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

In [15]:
ortak_diller = A.intersection(B)
ortak_diller

{'Python', 'SQL'}

In [16]:
sadece_A = A.difference(B)
sadece_A

{'Java', 'R'}

In [17]:
birlesimi = A.union(B)
birlesimi

{'C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL'}

Soru 4 – Modüller
• random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
• Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [18]:
import random
import statistics

In [20]:
sayilar= random.sample(range(1, 101), 10)
sayilar

[68, 80, 28, 23, 75, 96, 27, 85, 15, 2]

In [21]:
ortalama = statistics.mean(sayilar)
s_sapma = statistics.stdev(sayilar)

In [22]:
print(f"Ortalama: {ortalama}, Standart Sapma: {s_sapma}")   

Ortalama: 49.9, Standart Sapma: 34.092847082961875


Soru 5 – Fonksiyonlar
kelime_sayacı(metin) adında bir fonksiyon yazın.
Fonksiyon verilen metindeki:
• toplam kelime sayısını
• en uzun kelimeyi
• en sık geçen kelimeyi döndürsün.

In [26]:
def Kelime_sayaci(metin):
  
    for char in ".,!?;:":
        metin = metin.replace(char, "")
        
    kelimeler = metin.lower().split()
    
    toplam_kelime = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    
    # Sıklık hesabı
    frekans = {}
    for kelime in kelimeler:
        frekans[kelime] = frekans.get(kelime, 0) + 1
        
    en_sik = max(frekans, key=frekans.get)
    
    return toplam_kelime, en_uzun, en_sik


In [27]:
Kelime_sayaci(" akşam akşam ödev yapıyorum ve evet çok yorgunum ama bir taraftan da yarın saabahın köründe dersim olduğu için yapmak zorundayım ")

(20, 'zorundayım', 'akşam')

Soru 6 – Gömülü Fonksiyonlar
Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
sayilar = [5, 12, 7, 18, 24, 3, 16]
• Sadece çift sayıları filtreleyin.
• Bu sayıların karelerini bulun.
• Karelerini azalan sırada sıralayın.

In [28]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

In [29]:
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
print("Çift sayılar:", cift_sayilar)


Çift sayılar: [12, 18, 24, 16]


In [30]:
kareler = list(map(lambda x: x**2, cift_sayilar))
print("Kareleri:", kareler)


Kareleri: [144, 324, 576, 256]


In [31]:
sirali_kareler = sorted(kareler, reverse=True)
print("Azalan sıralı kareler:", sirali_kareler)


Azalan sıralı kareler: [576, 324, 256, 144]


Soru 7 – Lambda İfadeleri
Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
Bunu sorted + lambda ile yapın.

In [32]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

In [34]:
Kelime_uzunlugu = sorted(kelimeler, key=lambda kelime: len(kelime))
print(Kelime_uzunlugu)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


Soru 8 – Metodlar
Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
yazın.
Örn: "abc12def3" → 12 + 3 = 15

In [35]:
string_ifade= "abc12def3"

In [37]:
import re

def rakam_toplami(metin):
    sayilar = re.findall(r'\d+', metin)
    return sum(int(sayi) for sayi in sayilar)
rakam_toplami(string_ifade)


15

Soru 9 – (Ekstra) Numpy 1
10 elemanlı bir numpy dizisi oluşturun.
• Elemanlar 0–50 arasında rastgele sayılar olsun.
• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun

In [39]:
import numpy as np
dizi = np.array([36, 15, 2, 28, 17, 11, 44, 17,29,47])

In [46]:
ortalama= np.mean(dizi)
s_sapma= np.std(dizi).round(2)  
max_deger= np.max(dizi)

print(f"Ortalama: {ortalama}, Standart Sapma: {s_sapma}, Maksimum Değer: {max_deger}")

Ortalama: 24.6, Standart Sapma: 13.94, Maksimum Değer: 47


Soru 10 – (Ekstra) Numpy 2
5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
• Her sütunun ortalamasını bulun.
• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun

In [47]:
matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)


Orijinal Matris:
 [[0.50194669 0.28490454 0.13052448 0.83129743 0.58819853]
 [0.82326491 0.69271867 0.31384586 0.55067129 0.704439  ]
 [0.45255868 0.7371271  0.35884385 0.97897487 0.45936318]
 [0.56033883 0.99547822 0.29873725 0.2486109  0.81948931]
 [0.57722494 0.51382033 0.99491049 0.29807897 0.04106557]]


In [48]:
sutun_ortalamalari = np.mean(matris, axis=0)
print("Sütun Ortalamaları:\n", sutun_ortalamalari)


Sütun Ortalamaları:
 [0.58306681 0.64480977 0.41937239 0.58152669 0.52251112]


In [49]:
binary_matris = (matris > 0.5).astype(int)
print("Binary Matris:\n", binary_matris)


Binary Matris:
 [[1 0 0 1 1]
 [1 1 0 1 1]
 [0 1 0 1 0]
 [1 1 0 0 1]
 [1 1 1 0 0]]
